### ISSUE TITLE
Results on PECAN dataset?

### ISSUE THREAD

**Issue by aggelos-michael-papadopoulos** [WangLabforComputationalBiology/NanoBERTa-ASP#1]
Are there any results on PECAN dataset? Paragraph model is the current state-of-art on this official paratope prediction dataset. But i do not see your results on this database which has an official train/val/test split based on homology/sequence similarity etc...

**Comment by flyboyleo** [comment]
@SaYQWQ

**Comment by SaYQWQ** [comment]
This is a good question. We only used the trained Paragraph model to comparision which used PECAN as training set. We did not uesd the PECAN dataset by ourselves.

**Comment by aggelos-michael-papadopoulos** [comment]
Ok i see thank you.
